Push Activation Matrix to Lower Triangular Matrix code to this repo
HIRO-group/roboskin pull request #31
Opened 2020-01-26 07:05 UTC by krishnachaitanya7

Changes made in this PR:
- Added algorithm to convert a matrix (which should be convertible to a LT matrix) to a LT matrix. This also outputs the LT matrix, the way the segments are arranged in the robot, reference segment.
- Added tests to check whether the algorithm is working or not.

2020-01-28 06:53 UTC, watakandai requested changes

2020-01-28 06:53 UTC, watakandai commented on tests/algorithm/lower_triangular_algorithm_check.py
> +        if not is_lt_matrix:
`self.assertTrue()`

2020-01-28 06:53 UTC, watakandai commented on tests/algorithm/lower_triangular_algorithm_check.py
> +            raise Exception("Test-2 Failed")
self.assertTrue()

2020-01-28 06:53 UTC, watakandai commented on tests/algorithm/lower_triangular_algorithm_check.py
> +        is_lt_matrix, _, _, _, _ = ConvertToLT(test_array).get_lt_matrix()
I actually want to see the actual matrix.

Compare with the given matrix like
```
expected_matrix = np.array([
[0, 0, 0, 0],
[1, 0, 0, 0],
[0, 1, 0, 0],
[0, 0, 1, 0],
[0, 0, 0, 1]])

self.asssertEqual(converted_matrix, expected_matrix)

2020-01-28 06:53 UTC, watakandai commented on tests/algorithm/lower_triangular_algorithm_check.py
> +        is_lt_matrix, _, _, _, _ = ConvertToLT(test_array).get_lt_matrix()
For numpy  array, use `numpy.testing.assert_array_equal` instead of `self.assertEqual`

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def __init__(self, input_matrix):
The main algorithm is in the constructor lol 
Please separate the features

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        This function will convert a numpy 1D array which is considered a binary number into a decimal number
I don't get what this is doing. 
It would be nice if could give an example in docstring

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        This methos id used to convert some number like 768 to 0.768. Basically used to add weight value
why not just divide by 1000?
`return my_number/1000`

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def matrix_is_square(self, input_array):
`is_square()` or `is_square_matrix()`

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def find_empty_ndarray(self, input_array):
similarly `exist_empty_ndarray`?

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def islowertriangular(self, input_array: np.ndarray):
`is_lower_triangular`

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        zero_array_index = []
from line 15 to 24, you could separate it as another function called `is_only_one_empty_row()` or something

2020-01-28 06:53 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def custom_sort_row(self, input_array: np.ndarray):
why custom!?

2020-01-28 07:03 UTC, krishnachaitanya7 commented on tests/algorithm/lower_triangular_algorithm_check.py
> +        if not is_lt_matrix:
Done!

2020-01-28 07:03 UTC, krishnachaitanya7 commented on tests/algorithm/lower_triangular_algorithm_check.py
> +            raise Exception("Test-2 Failed")
Done!, I thought I pushed it, but it was old, getting confused with 2 PC's lol.

2020-01-28 07:04 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def __init__(self, input_matrix):
LOL, yeah, Will change it

2020-01-28 07:06 UTC, krishnachaitanya7 commented
@watakandai after going through your comments, I realized I need to update the docstrings more. Will do it now!

2020-02-02 20:53 UTC, krishnachaitanya7 commented on tests/algorithm/lower_triangular_algorithm_check.py
> +        is_lt_matrix, _, _, _, _ = ConvertToLT(test_array).get_lt_matrix()
Excellent point! Done!

2020-02-02 21:07 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def __init__(self, input_matrix):
Changed

2020-02-02 21:07 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        This function will convert a numpy 1D array which is considered a binary number into a decimal number
Done!

2020-02-02 21:10 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        This methos id used to convert some number like 768 to 0.768. Basically used to add weight value
Because sometimes I would have to convert two digit numbers like 78 to 0.78. This number is basically a weight for the argsort, hence dividing by 1000 may sometimes lead to weird results. Hence! I have also explained the algorithm in the docstring at the top of the file.

2020-02-02 21:11 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def matrix_is_square(self, input_array):
renamed it to is_square_matrix. Thanks!

2020-02-02 21:12 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def find_empty_ndarray(self, input_array):
renaming it to find_zero_ndarray as I feel it's more appropriate. Lemme know

2020-02-02 21:13 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def islowertriangular(self, input_array: np.ndarray):
Good point. Thanks!

2020-02-02 21:14 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        zero_array_index = []
I have added that functionality in the main algorithm! Lemme know

2020-02-02 21:16 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def custom_sort_row(self, input_array: np.ndarray):
It's because it's totally made by me, and I don't know if such algorithm exists, should come up with better name LOL. Please suggest me a better name.

2020-02-02 22:15 UTC, krishnachaitanya7 commented
I have made all changes, added TLDR what are done in this PR.
![code_review_meme](https://user-images.githubusercontent.com/9385832/73616289-cf329680-45ce-11ea-9113-1087384b8a87.png)

2020-02-03 18:58 UTC, watakandai requested changes
Most of them are wonderful. It's just the matter of the variable and function names, and also how the code is structured.

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def main_algorithm(self):
still too large and hard to understand what is going on in this function

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        zero_array_index = []
I still recommend separating each feature as a function e,g, `is_only_one_empty_row`

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/__init__.py
> +from .convert_to_lowertriangular_matrix import ConvertToLT
I often see people importing in `__init__.py` file. Why do people do this?

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    *) If there is a tie in number of ones, then you assume the row as a binary number, with MSB at first and then the
Most Significant Bit?

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        input_matrix = self.custom_sort_row(self.input_matrix)
I thought it would be nice to name it `sort_row_in_ascending_order` and `sort_column_in_descending_order`, so it is easier for others to understand. What do you think?

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        self.rows += np.array((self.rows - zero_array_index[0] + 1) > 0).astype(int) + 1
What does this line do?

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def get_lt_matrix(self):
maybe `get_lt_matrix_infos` ?

2020-02-03 18:58 UTC, watakandai commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +            input_matrix = np.insert(input_matrix, 0, 0, axis=0)
Could it be better to make it a function?

2020-02-03 19:38 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def main_algorithm(self):
Done!

2020-02-03 19:42 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/__init__.py
> +from .convert_to_lowertriangular_matrix import ConvertToLT
So that when they pip install, they can import it directly. If it's not mentioned in __init__ the module can't be imported.

2020-02-03 19:44 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    *) If there is a tie in number of ones, then you assume the row as a binary number, with MSB at first and then the
For example take a row which is [1, 0, 0, 1, 0], now you assume this is a binary number, then leftmost bit in this case 1 is MSB, and 0 is LSB(Least significant bit)

2020-02-03 20:11 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        input_matrix = self.custom_sort_row(self.input_matrix)
Done!

2020-02-03 20:11 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +        self.rows += np.array((self.rows - zero_array_index[0] + 1) > 0).astype(int) + 1
Added comments!

2020-02-03 20:18 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +    def get_lt_matrix(self):
Done!

2020-02-03 20:18 UTC, krishnachaitanya7 commented on robotic_skin/algorithm/convert_to_lowertriangular_matrix.py
> +            input_matrix = np.insert(input_matrix, 0, 0, axis=0)
Great Idea. Made it a new function. Thanks!

2020-02-03 20:19 UTC, krishnachaitanya7 commented
@watakandai Addressed all changes. Thank you.

2020-02-04 05:25 UTC, watakandai approved these changes

2020-02-04 05:26 UTC, watakandai commented
lgtm

2020-02-04 05:28 UTC, watakandai commented
![](https://media0.giphy.com/media/3o7abB06u9bNzA8lu8/giphy.gif?cid=790b76114baa61e6ef603afa6ecfc59a44019ae116c5595a&rid=giphy.gif)

2020-02-04 18:04 UTC, krishnachaitanya7 commented
Perfect! Thanks!

2020-02-04 18:05 UTC, merged