pylint ignore
HIRO-group/roboskin pull request #44
Opened 2020-02-08 22:37 UTC by peasant98

addressing issue from https://github.com/HIRO-group/robotic_skin/issues/43; ignoring pylint for two files.

2020-02-08 23:50 UTC, watakandai requested changes

2020-02-08 23:50 UTC, watakandai commented on examples/07_read_vcnl4040.py
> +
oh no need to modify this. Could you just remove these two files? We do not need it anymore

2020-02-09 04:39 UTC, peasant98 commented on examples/07_read_vcnl4040.py
> +
Ah ok, will take care of that.

2020-02-09 08:46 UTC, krishnachaitanya7 requested changes
Are the files deleted permanently?

2020-02-09 15:50 UTC, peasant98 commented
yes

2020-02-09 17:55 UTC, merged