Proximity avoidance example
HIRO-group/roboskin pull request #56
Opened 2020-03-07 01:10 UTC by aran159

Code organization changed
VL53L1X_ProximitySensor class: range_value working, added stop method to fix problem when running code again, changed some things in the documentation

2020-03-07 01:14 UTC, krishnachaitanya7 requested changes

2020-03-07 01:14 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
Shouldn't rospy.init_node come first?

2020-03-07 01:14 UTC, krishnachaitanya7 commented on robotic_skin/sensor/vl53l1x.py
> +            self.tof.set_timing(timing_budget, inter_measurement_period)
The naming is way better than mine. Pretty good! Thanks for this!

2020-03-07 01:16 UTC, krishnachaitanya7 commented
Please resolve the conflicting files @aran159. Thanks!

2020-03-07 01:18 UTC, krishnachaitanya7 commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
The ranging integer starts from 1. Ref: https://pypi.org/project/VL53L1X/. What is 0 for?

2020-03-07 01:38 UTC, peasant98 approved these changes

2020-03-07 01:38 UTC, peasant98 commented on robotic_skin/sensor/proximity_publisher.py
> +        pass
I would do something here, to let the user know that you won't be publishing proximity.

2020-03-07 01:38 UTC, peasant98 commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
you can do `range(1,4)` here.

2020-03-07 01:38 UTC, peasant98 commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
what needs to be done here?

2020-03-07 01:38 UTC, peasant98 commented on robotic_skin/sensor/vl53l1x.py
> +    def stop(self):
where is this function used? Also, try to have functions and imports out of main.

2020-03-07 02:25 UTC, aran159 commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
That's true! It was working but it makes sense

2020-03-07 02:29 UTC, aran159 commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
I saw somewhere that it meant no range option. The 0 option works but I don't know the difference with the LONG range option. It was the option Caleb was using in the last working code. Should I keep it as an option or do I delete it?

2020-03-07 02:29 UTC, aran159 commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
> you can do `range(1,4)` here.

Thank you for the advice!

2020-03-07 02:30 UTC, aran159 commented on robotic_skin/sensor/vl53l1x.py
> +            self.tof.set_timing(timing_budget, inter_measurement_period)
Thank you

2020-03-07 02:33 UTC, aran159 commented on robotic_skin/sensor/proximity_publisher.py
> +        pass
Ok!

2020-03-07 02:35 UTC, aran159 commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
This was included before I started editing it. It is a method for calibrating values. Right now it just returns the same data it receives, but do we want to implement something here in the future?

2020-03-07 02:37 UTC, aran159 commented on robotic_skin/sensor/vl53l1x.py
> +    def stop(self):
`def publish_proximity():
    rospy.init_node('proximity_publisher', anonymous=True)
    pub = rospy.Publisher('/proximity/y', Int16, queue_size=10)
    rate = rospy.Rate(100) #10hz
    ps = vl53l1x.VL53L1X_ProximitySensor()

    while not rospy.is_shutdown():
        proximity = ps.read()
        print(proximity, type(proximity))
        pub.publish(proximity)
        rate.sleep()
    ps.stop()`

It is used here. It stops the tof object.

2020-03-07 02:50 UTC, aran159 commented on robotic_skin/sensor/vl53l1x.py
> +    def stop(self):
> where is this function used? Also, try to have functions and imports out of main.

I don't know where I'm doing this. Can you help me with that please?

2020-03-07 04:08 UTC, peasant98 commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
@watakandai thoughts?

2020-03-07 04:48 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
Maybe Caleb ha written this, but guess is that he might have thought that the calibration might be required if we were to incorporate the skin in the polymer materials. It might change the sensor's behavior. We don't need to implement it now because the proximity sensor is just laid on top of the skin unit.

2020-03-07 05:09 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
How about putting a name for each constant, so that it is easier to understand which option you are choosing from, or do we not need this for such as short script? @krishnachaitanya9

2020-03-07 05:10 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
If not, then I would stick with `[1,2,3]`, since you are choosing from the list. 
`range(1,4)` looks like you are looping over some range ...

2020-03-07 05:11 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +    def stop(self):
Any idea? @krishnachaitanya9

2020-03-07 05:16 UTC, watakandai requested changes

2020-03-07 05:16 UTC, watakandai commented on robotic_skin/sensor/proximity_publisher.py
> +        print(proximity, type(proximity))
Remove this line when merging to master, or add 
```
def publish_proximity(debug=False):
...
if debug:
    print(proximity) 
```

```
debug = sys.argv[1]
publish_proximity(debug)
```

2020-03-07 05:16 UTC, watakandai commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
Let's create a Proximity Msg in the future. @krishnachaitanya9 @peasant98

2020-03-07 20:36 UTC, calebescobedo commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
I'll look for the reference I got the information from, but the reason I set it to 0 initially is that someone mentioned it was the custom setting. I think that's why Krishna could not make the publishing rate any faster initially, but with zero you can set the publishing rate to anything >50hz.

2020-03-07 20:38 UTC, calebescobedo commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
I included it because Krishna included it in the original file and I just copied his file and edited it to publish my proximity values. I don't think it's needed at all for this code. Are you going to need to. calibrate the proximity sensors in the future? Does anyone know how accurate they are right now?

2020-03-07 20:44 UTC, calebescobedo commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
From the Github page https://github.com/pimoroni/vl53l1x-python they made a comment about setting an explicit timing budget use zero. 

<img width="563" alt="Screen Shot 2020-03-07 at 1 42 44 PM" src="https://user-images.githubusercontent.com/37485219/76152169-91b3a400-6079-11ea-827d-cd673f8a4beb.png">

2020-03-08 18:00 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
Let's add the same comment to our code too

2020-03-08 18:06 UTC, watakandai requested changes

2020-03-08 18:06 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
We might need it in the future, but not right now. 
The accuracy should be written in the sensor's official documentation. 

We can remove it if it is not required. Please look into the `Sensor` class to check whether we need it or not since `VL53L1X_ProximitySensor` inherits from the `Sensor` class.

2020-03-10 09:49 UTC, krishnachaitanya7 commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
![image](https://user-images.githubusercontent.com/9385832/76300223-fd685d80-6281-11ea-890e-9e80785d211c.png)
The datasheet says only 3 modes. We need to dig deep into it and only set values according to that. Set the timing budget exactly. I will work with @aran159 A$AP and come with a good solution. Thanks!

2020-03-10 09:52 UTC, krishnachaitanya7 commented on robotic_skin/sensor/vl53l1x.py
> +        #TODO
I just included it as the class needs to be overridden. Also, I wanted to find a good pythonic way to use that in the future.  Maybe now is the best time. Exciting times!

2020-03-10 09:56 UTC, krishnachaitanya7 commented on robotic_skin/sensor/vl53l1x.py
> +    def stop(self):
It's given in the main library as a way to stop getting values: https://pypi.org/project/VL53L1X/

2020-03-10 09:58 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
Aye Aye Capitan!

2020-03-10 09:58 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
Lemme add it beautiful kanban

2020-03-10 09:59 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
Added!

2020-03-10 10:00 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +        print(proximity, type(proximity))
I like 2nd option. Is that okay with you? @watakandai

2020-03-10 18:41 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
Will this be good @watakandai : http://docs.ros.org/melodic/api/sensor_msgs/html/msg/Range.html ?

2020-03-10 18:53 UTC, watakandai commented on robotic_skin/sensor/proximity_publisher.py
> +    rospy.init_node('proximity_publisher', anonymous=True)
👍

2020-03-10 18:53 UTC, watakandai commented on robotic_skin/sensor/proximity_publisher.py
> +        print(proximity, type(proximity))
Agree. Do you know how we can pass a default value?

2020-03-10 18:53 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +    def stop(self):
I see

2020-03-11 19:41 UTC, krishnachaitanya7 commented
![image](https://user-images.githubusercontent.com/9385832/76456992-94760800-639d-11ea-8929-3a96c708cc77.png)
According to the datasheet 33ms timing budget is best for all ranges. So I set the timing budget to 33ms and inter measurement period to 33ms so that we can get the fastest possible FPS. Right now the graph which @aran159 had problems with looks good I think.

2020-03-11 19:58 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
@krishnachaitanya9 Can you describe what had happened when you specify `start_ranging()` and `set_timing()`  here? 
Thanks

2020-03-11 21:41 UTC, krishnachaitanya7 commented on robotic_skin/sensor/vl53l1x.py
> +        if range_value in (0, 1, 2, 3):
So when I did tof.start_ranging(1 or 2 or 3), the vl53l1x library sets its own set of values according to the number passed. 

But if we want to set the timing budgets ourself we have to put o according to [1] and then set our own timing budget values

According to the datasheet, the best value to set which work for all ranges is 33ms
![image](https://user-images.githubusercontent.com/9385832/76467101-7e247800-63ae-11ea-99c2-c22540f0da02.png)
Then I set the values accordingly as quoted in my previous comment here in this PR:

> ![image](https://user-images.githubusercontent.com/9385832/76456992-94760800-639d-11ea-8929-3a96c708cc77.png)
> According to the datasheet 33ms timing budget is best for all ranges. So I set the timing budget to 33ms and inter measurement period to 33ms so that we can get the fastest possible FPS. Right now the graph which @aran159 had problems with looks good I think.

References:
[1] https://pypi.org/project/VL53L1X/

Thanks!

2020-03-12 01:38 UTC, krishnachaitanya7 commented
Note: If you don't put inter measurement period and timing budget you will get weird spikes

2020-03-12 01:42 UTC, krishnachaitanya7 approved these changes

2020-03-12 01:42 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    pub = rospy.Publisher('/proximity', Range, queue_size=10)
@aran159 I changed /proximity/y to /proximity. Is that okay?

2020-03-12 17:11 UTC, watakandai commented on robotic_skin/sensor/proximity_publisher.py
> +    pub = rospy.Publisher('/proximity', Range, queue_size=10)
👍

2020-03-12 18:23 UTC, aran159 commented on robotic_skin/sensor/proximity_publisher.py
> +    pub = rospy.Publisher('/proximity', Range, queue_size=10)
Yes! That needs to be changed in @calebescobedo 's examples also then.

2020-03-12 18:46 UTC, calebescobedo commented on robotic_skin/sensor/proximity_publisher.py
> +    pub = rospy.Publisher('/proximity', Range, queue_size=10)
We need to change the message type then so that we can carry the information about which proximity sensor is sending the information. For example, the IMU's have a topic for each individual IMU counting from 0-6. We should do something similar here.

2020-03-12 19:20 UTC, krishnachaitanya7 commented on robotic_skin/sensor/proximity_publisher.py
> +    pub = rospy.Publisher('/proximity', Range, queue_size=10)
The message type is range. As this is just an example of proximity publisher, the names are okay I guess. When in actual deployment, this can't be used directly. Something similar to what I made in PandaDeployment folder should be made again.

2020-03-13 07:53 UTC, krishnachaitanya7 commented
Hi all. As per Kandai's request, I am moving all publishers to ros_robotic_skin to keep the repository clean of rospy imports. I have noted down all your comments and will be making changes and raising new PR's. Please and Thank you.

2020-03-15 08:26 UTC, krishnachaitanya7 commented
Only 2 files are changed:
- proximity_publisher.py
- vl53l1x.py

vl53l1x.py stays here. proximity_publisher.py is moved to ros_robotic_skin repo, PR: https://github.com/HIRO-group/ros_robotic_skin/pull/64. Please review it there. I have also added the latest commit ID for reference when reviewing. 

Now I am going to delete the proximity_publisher.py from here.

Thank you for your continued patience.

2020-03-15 15:54 UTC, watakandai requested changes

2020-03-15 15:54 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        input_value : float (in mm)
`(in mm)` in the next line please

2020-03-15 15:54 UTC, watakandai commented on robotic_skin/sensor/vl53l1x.py
> +        float (in m A/C to ROS standards for )
This aswell.

2020-03-15 15:55 UTC, watakandai commented
Other than the requested changes, it looks good to go

2020-03-15 17:06 UTC, watakandai approved these changes

2020-03-15 17:07 UTC, krishnachaitanya7 commented
Thanks, merging this now

2020-03-15 17:07 UTC, merged