New Accelerometer Publisher
HIRO-group/roboskin pull request #58
Opened 2020-03-12 18:13 UTC by krishnachaitanya7

Added a new Accelerometer Publisher. Features:
- Sets Environment variables. No need to look into the bashrc files and check if everything is correct or not. All at one place
- Tested and working in RPi

2020-03-12 18:22 UTC, peasant98 reviewed
Since this is python3, can you use `f-strings?`

2020-03-12 18:24 UTC, krishnachaitanya7 commented
Great Idea. Will change it right now

2020-03-12 18:27 UTC, peasant98 commented
Cool!

2020-03-12 18:38 UTC, watakandai requested changes

2020-03-12 18:38 UTC, watakandai commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
Better to make it an argument with this number as a default value.

2020-03-12 18:41 UTC, krishnachaitanya7 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
Just now realized it's bad because these IP addresses need to be changed every time. So there will be a useless commit every time. So making a JSON file and I will be reading from that itself so that they can be changed all times.

2020-03-12 18:59 UTC, krishnachaitanya7 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
Done. Can you please check again if that's okay?

2020-03-12 19:00 UTC, krishnachaitanya7 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
@watakandai

2020-03-12 19:18 UTC, watakandai commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
Does that mean everyone has to make that json file???? That's annoying too. What do you think? @peasant98

2020-03-12 21:20 UTC, peasant98 commented on robotic_skin/publishers/accelerometer_publisher.py
> +# Global Variables
is this comment needed?

2020-03-12 23:02 UTC, peasant98 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
why do we need a json file?

2020-03-12 23:02 UTC, watakandai commented on robotic_skin/publishers/accelerometer_publisher.py
> +# Global Variables
no

2020-03-12 23:03 UTC, peasant98 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
Maybe consider looking into: https://docs.python.org/3/howto/argparse.html

2020-03-12 23:03 UTC, peasant98 commented on robotic_skin/publishers/accelerometer_publisher.py
> +# Global Variables
I don't see any global variables here.

2020-03-12 23:04 UTC, krishnachaitanya7 commented on robotic_skin/publishers/accelerometer_publisher.py
> +# Global Variables
It was a comment from before. Removing it. Actually moving the entire file to ros_robotic_skin

2020-03-12 23:06 UTC, krishnachaitanya7 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
Argparse is a very good option. But the command required to run would be very long. But I am okay with either. So what do you guys vote on?

2020-03-12 23:51 UTC, peasant98 commented on robotic_skin/publishers/accelerometer_publisher.py
> +# Global Variables
cool

2020-03-13 00:38 UTC, krishnachaitanya7 commented on robotic_skin/sensor/accelerometer_publisher.py
> +RPi_IP = '192.168.50.31'  # The IP of RPi which will be sending packets
@peasant98 @watakandai?

2020-03-13 02:30 UTC, aran159 approved these changes

2020-03-13 07:52 UTC, krishnachaitanya7 commented
Hi all. As per Kandai's request, I am moving all publishers to ros_robotic_skin to keep the repository clean of rospy imports. I have noted down all your comments and will be making changes and raising new PR's. Please and Thank you.

2020-03-13 08:18 UTC, watakandai commented
thanks. this repo should be independent from ROS system.

2020-03-13 19:54 UTC, calebescobedo approved these changes

2020-03-15 08:21 UTC, krishnachaitanya7 commented
I have moved all changes to ros_robotic_skin in here: https://github.com/HIRO-group/ros_robotic_skin/pull/64. Please review it there. Thank you for your patience.

2020-03-15 08:21 UTC, closed without merging