Change sensor structure
HIRO-group/roboskin pull request #63
Opened 2020-03-19 10:01 UTC by krishnachaitanya7

- Made compatible with Python2.7 Issue #60 
- Now sensor class reads yaml config files and sets environment variables automatically
- Removed test connections.py as it would be better to test all boards with the command I included in README, in subsection "Testing Hardware"

TODO: Remove unused not required imports so that all requirements can be easily installed in Python2.7 environment. I haven't touched those, so as to decide which are required and get you guy's view.  A/C to me only just a couple of them to stay, rest should go.

2020-03-19 20:11 UTC, watakandai requested changes

2020-03-19 20:11 UTC, watakandai commented on README.md
> +Target Python version is 2.7
but doesn't it also work on 3.6? Are you assuming that ROS can only handle 2.7?

2020-03-19 20:11 UTC, watakandai commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
Do you need this? I think it's intuitive for git users.

2020-03-19 20:11 UTC, watakandai commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
same here

2020-03-19 20:11 UTC, watakandai commented on README.md
> +
any image?

2020-03-19 20:11 UTC, watakandai commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
what is `params.yml`? and why are you merging two dictionaries? Aren't there supposed to be only 1 config file?

2020-03-19 20:31 UTC, krishnachaitanya7 commented on README.md
> +Target Python version is 2.7
I am assuming that ROS can only handle Python2.7. So I making it 2.7 so that in the future if somebody develops, they will do so in 2.7

2020-03-19 20:32 UTC, krishnachaitanya7 commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
It's definitely intuitive, but just want to put it here so that if user forgets it this would be a quick reminder to use this. I am okay with either. Kindly lemme know.

2020-03-19 20:33 UTC, krishnachaitanya7 commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
t's definitely intuitive, but just want to put it here so that if user forgets it this would be a quick reminder to use this. I am okay with either. Kindly lemme know.

2020-03-19 20:33 UTC, krishnachaitanya7 commented on README.md
> +
Ahh! Good idea, I will add it

2020-03-19 20:47 UTC, krishnachaitanya7 commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
So params.yaml has gravitational constant, so I include params.yaml here. In the future, if we have to include some other yaml and use it in this repo, we can do it by adding in the list here. 

The yaml files are two types: (1) Which applies to all and probably should be included by all. Example params.yaml  has gravitational constant, which should be used by LSM6DS3 class. (2) Next is class-specific yaml like the config publisher_variables.yaml, which we are passing as an argument. This config yaml contains ROS_IP etc.

The code assumes that all yaml's are in the same directory of the argument config file.

2020-03-19 21:05 UTC, watakandai commented on README.md
> +Target Python version is 2.7
k

2020-03-19 21:06 UTC, watakandai commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
@peasant98 what do you think?

2020-03-19 21:07 UTC, watakandai commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
There already exists a constant file.
https://github.com/HIRO-group/robotic_skin/blob/ChangeSensorStructure/robotic_skin/const.py

2020-03-19 21:09 UTC, watakandai commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
For yaml file, we only need those that contains the environmental variables or some kind of configuration

2020-03-19 21:16 UTC, krishnachaitanya7 commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
Sure. So the const needs to be changed to add gravitational constant. I remember from some of our previous discussions regarding the best way to declare constants and finally, yaml was decided so that everybody can include it rather than a py file. Do you still want to go with const.py?

2020-03-19 21:17 UTC, watakandai commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
I haven't said that. Constants should be in const.py

2020-03-19 21:22 UTC, krishnachaitanya7 commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
Sure! const.py it is

2020-03-19 23:12 UTC, watakandai commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
:+1:

2020-03-22 04:16 UTC, krishnachaitanya7 commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
removed the lines!

2020-03-22 04:16 UTC, krishnachaitanya7 commented on README.md
> +Where ChangeSensorStructure is the branch name and it may vary in your case
removed!

2020-03-22 04:16 UTC, krishnachaitanya7 commented on README.md
> +
Added

2020-03-22 04:33 UTC, krishnachaitanya7 commented on robotic_skin/sensor/sensor.py
> +        required_config_files = ['params.yaml']
Changed to including everything from const.py

2020-03-22 05:27 UTC, peasant98 approved these changes
lgtm

2020-03-22 05:35 UTC, watakandai requested changes

2020-03-22 05:35 UTC, watakandai commented on README.md
> +![](images/hardware_test.png)
:+1:

2020-03-22 05:35 UTC, watakandai commented on robotic_skin/sensor/lsm6ds3_accel.py
> +from ..const import GRAVITATIONAL_CONSTANT
can you import like
```
from robotic_skin.const import GRAVITATIONAL_CONST
```

2020-03-22 05:38 UTC, krishnachaitanya7 commented on robotic_skin/sensor/lsm6ds3_accel.py
> +from ..const import GRAVITATIONAL_CONSTANT
fantastic idea. Will do so

2020-03-22 05:41 UTC, krishnachaitanya7 commented on robotic_skin/sensor/lsm6ds3_accel.py
> +from ..const import GRAVITATIONAL_CONSTANT
Done!

2020-03-22 05:45 UTC, watakandai approved these changes

2020-03-22 05:48 UTC, merged

2020-03-22 05:48 UTC, krishnachaitanya7 commented
Thanks @watakandai and @peasant98 for taking time to look!