Refactoring to add more variations for the optimizer
HIRO-group/roboskin pull request #68
Opened 2020-03-31 22:55 UTC by watakandai

![estimated_imu](https://user-images.githubusercontent.com/11141442/78113229-ab1be780-73bc-11ea-8a18-df3189efcf9e.gif)

2020-04-01 17:03 UTC, peasant98 requested changes
Main thing is, could you add more docstrings, and also add some steps in readme how to run?

2020-04-01 17:03 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> +def max_acceleration_joint_angle(curr_w, max_w, t):
explain the function parameters a bit more here.

2020-04-01 17:03 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> +def constant_velocity_joint_angle(curr_w, max_w, t):
docstring

2020-04-01 17:03 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> +class ErrorFunctions():
what will this be for?

2020-04-01 17:03 UTC, peasant98 commented on robotic_skin/calibration/optimizer.py
> +    """
docstring here?

2020-04-01 17:03 UTC, peasant98 commented on robotic_skin/calibration/plot_data.py
> +def estimate_acceleration_analytically(Tdofs, Tjoints, Tdofi2su, d, i, curr_w):
this is defined in another file; can you import it instead?

2020-04-03 03:04 UTC, watakandai commented on robotic_skin/calibration/optimizer.py
> +        `error_functions`:
dictionary

2020-04-03 03:04 UTC, watakandai commented on robotic_skin/calibration/utils.py
>  def quaternion_from_two_vectors(source, target):
we might not need this. We may need to delete this function

2020-04-03 03:05 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +class ErrorFunctions():
A error function base class

2020-04-03 03:07 UTC, watakandai commented on robotic_skin/calibration/plot_data.py
> +def estimate_acceleration_analytically(Tdofs, Tjoints, Tdofi2su, d, i, curr_w):
ah true. 
When I made this file, I didn't make the function that general. That's why I didn't import it from other file, but now I think we should

2020-04-03 04:40 UTC, peasant98 commented
ARM OF GOD

2020-04-03 04:40 UTC, merged