update error function based on mittendorfer's paper
HIRO-group/roboskin pull request #70
Opened 2020-04-04 23:16 UTC by peasant98

updating error function based on mittendorfer's paper; more specifically, the dynamic acceleration loss function.

2020-04-20 17:43 UTC, watakandai commented on robotic_skin/calibration/accel_position.py
> +            optimize_all_params = False
how about you do this in `arg_parse()`?

2020-04-20 17:43 UTC, watakandai commented on robotic_skin/calibration/accel_position.py
> +            'Translation': MaxAccelerationErrorFunction(data, L1Loss(hyperparams))
we need to change our code so that we can switch the error functions easily

2020-04-20 17:43 UTC, watakandai commented on robotic_skin/calibration/accel_position.py
> +    data = Data(static, dynamic, constant)
same here. Is there any good way to be able to switch data? easily???

2020-04-20 17:43 UTC, watakandai commented on robotic_skin/calibration/utils.py
> +            return self.Tdof2dof[:max(0, i+1)]
did I make a mistake here? what went wrong with `self.Tdof2dof[:max(0, i)]`?

2020-04-20 17:43 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +    accel_su = np.dot(dof_T_su.R.T, a_dofd) + np.dot(Rrs2su, accel_rs)
I'll go through the equation again.

2020-04-20 17:47 UTC, peasant98 commented on robotic_skin/calibration/accel_position.py
> +            optimize_all_params = False
ah, will do.

2020-04-20 17:47 UTC, peasant98 commented on robotic_skin/calibration/accel_position.py
> +    data = Data(static, dynamic, constant)
I will work on that.

2020-04-20 17:49 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> +    accel_su = np.dot(dof_T_su.R.T, a_dofd) + np.dot(Rrs2su, accel_rs)
sounds good.

2020-04-22 17:02 UTC, watakandai requested changes

2020-04-22 17:02 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +    accel_su = np.dot(dof_T_su.R.T, a_dofd) + np.dot(Rrs2su, accel_rs)
I think this is correct.
Let's make it optional which method to use.

2020-04-22 17:42 UTC, peasant98 commented on robotic_skin/calibration/accel_position.py
> +    data = Data(static, dynamic, constant)
it will load all.

2020-04-22 17:43 UTC, peasant98 commented on robotic_skin/calibration/utils.py
> +            return self.Tdof2dof[:max(0, i+1)]
we discussed, the above change is good to go.

2020-04-22 18:10 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> +    accel_su = np.dot(dof_T_su.R.T, a_dofd) + np.dot(Rrs2su, accel_rs)
sounds good

2020-04-30 17:45 UTC, peasant98 commented
support for both mittendorfer (the one we think it should be and the one defined in the paper) is now up. You just have to specify a bool in one of the arguments for the max acceleration function that mittendorfer used.

2020-04-30 20:25 UTC, watakandai commented
Perfect.
I asked the author and he hasn't clearly answered which method he used.
Now, he doesn't reply anymore. 
We can go further and compare with both methods. :+1: 

![Screenshot from 2020-04-30 14-23-47](https://user-images.githubusercontent.com/11141442/80755603-5cae5580-8aee-11ea-80f9-8dd83c2463a3.png)

2020-04-30 20:27 UTC, watakandai approved these changes

2020-04-30 20:27 UTC, watakandai commented
LGTM. Let's get some result as a table.

2020-04-30 20:49 UTC, peasant98 commented
yay, all github actions are passing!

2020-04-30 20:49 UTC, merged