Add quaternion degrees method
HIRO-group/roboskin pull request #72
Opened 2020-04-22 17:46 UTC by krishnachaitanya7

- Add degree between quaternion method
- Add test method to calculate the degree between quaternions

2020-04-22 18:41 UTC, peasant98 approved these changes
LGTM

2020-04-22 19:30 UTC, watakandai requested changes

2020-04-22 19:30 UTC, watakandai commented on robotic_skin/calibration/utils.py
> +    angle_in_degrees = (angle / np.pi) * 180
I think rad is alright.

2020-04-22 20:31 UTC, krishnachaitanya7 commented on robotic_skin/calibration/utils.py
> +    angle_in_degrees = (angle / np.pi) * 180
So I should be returning angle which is in radians? @watakandai

2020-04-22 23:11 UTC, watakandai commented on robotic_skin/calibration/utils.py
> +    angle_in_degrees = (angle / np.pi) * 180
yeah

2020-04-23 01:53 UTC, krishnachaitanya7 commented on robotic_skin/calibration/utils.py
> +    angle_in_degrees = (angle / np.pi) * 180
Done

2020-04-23 02:49 UTC, merged