[WIP] - Torch optimize
HIRO-group/roboskin pull request #79
Opened 2020-05-18 00:14 UTC by peasant98

This PR gives users the option to optimize with Pytorch's automatic differentiation engine. It's still WIP, but raising it now to see the progress of this branch in relation to master.

2020-05-18 03:48 UTC, watakandai requested changes

2020-05-18 03:48 UTC, watakandai commented on robotic_skin/calibration/transformation_matrix.py
> +        self.matrix = self.transformation_matrix(*self.params)
I'm afraid these things do not work for the TransformationMatrix which results from the dot product of two other TransformationMatrix `T = Ti * Tj`, since it does no longer hold `self.params`

2020-05-18 04:41 UTC, peasant98 commented on robotic_skin/calibration/transformation_matrix.py
> +        self.matrix = self.transformation_matrix(*self.params)
yea

2020-05-18 05:02 UTC, watakandai requested changes

2020-05-18 05:02 UTC, watakandai commented on robotic_skin/calibration/transformation_matrix.py
> +        new_matrix = self.mm_fnc(self.matrix, T.matrix)
What if they had different class type?
What would be the resulting new_matrix class type?

And is this in a correct position? I believe this should be below `T.matrix = new_matrix`
```python
        if self.is_tensor:
            T.tensor_()
```

2020-05-18 05:11 UTC, peasant98 commented on robotic_skin/calibration/transformation_matrix.py
> +        new_matrix = self.mm_fnc(self.matrix, T.matrix)
updated.

2020-05-31 23:19 UTC, watakandai requested changes

2020-05-31 23:19 UTC, watakandai commented on examples/calibration/calibrate_imu_poses.py
> +#!/usr/bin/env python
I moved the script under the directory called `robotic_skin/robotic_skin/examples/calibration/`

2020-05-31 23:19 UTC, watakandai commented on robotic_skin/calibration/loss.py
> +        return np.mean(np.sum(x))
you forgot `np.abs()`

2020-05-31 23:19 UTC, watakandai commented on robotic_skin/calibration/loss.py
>          return mean_absolute_error(x_target, x_estimated)
These classes must be able to handle both a singular array and multi-dimension arrays.

2020-05-31 23:19 UTC, watakandai commented on robotic_skin/calibration/transformation_matrix.py
> +            temp_params = np.array([theta.cpu(), d.cpu(), a.cpu(), alpha.cpu()], dtype=float)
why do you have 2 `temp_params`

2020-05-31 23:19 UTC, watakandai commented on robotic_skin/calibration/kinematic_chain.py
> +import torch
Don't forget to add the modifications I made in the last PR.

2020-05-31 23:20 UTC, peasant98 commented on robotic_skin/calibration/kinematic_chain.py
> +import torch
yea, many are coming

2020-05-31 23:20 UTC, peasant98 commented on robotic_skin/calibration/loss.py
> +        return np.mean(np.sum(x))
ah, thx

2020-05-31 23:21 UTC, peasant98 commented on robotic_skin/calibration/loss.py
> +        return np.mean(np.sum(x))
fixed

2020-05-31 23:21 UTC, peasant98 commented on examples/calibration/calibrate_imu_poses.py
> +#!/usr/bin/env python
yea, going to delete this.

2020-05-31 23:26 UTC, peasant98 commented on examples/calibration/calibrate_imu_poses.py
> +#!/usr/bin/env python
yea, thx

2020-06-01 00:44 UTC, peasant98 commented on robotic_skin/calibration/kinematic_chain.py
> +import torch
all is updated.

2020-06-01 05:27 UTC, peasant98 commented on robotic_skin/calibration/loss.py
>          return mean_absolute_error(x_target, x_estimated)
yep, they can

2020-06-04 06:44 UTC, peasant98 commented
finally, the green check mark is there.

2020-06-05 03:48 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> -        kinemaic_chain:
Thanks :+1:  LOL

2020-06-05 03:56 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> -        kinemaic_chain:
yep

2020-06-06 03:53 UTC, watakandai requested changes

2020-06-06 03:53 UTC, watakandai commented on robotic_skin/calibration/transformation_matrix.py
> +        qz = pyqt.Quaternion(axis=[0, 0, 1], angle=temp_params[0])
Why don't you first run
```
params = np.array([theta, d, a, alpha], dtype=float)
self.params = np.nan_to_num(params)
```

and then 
1. set quaternions
2. convert it to tensor. 

Then you don't really need such a long if statement and `temp_params`

2020-06-06 03:56 UTC, watakandai commented on robotic_skin/calibration/optimizer.py
> +class TorchOptimizerBase(IncrementalOptimizerBase):
Can you add comments on what each algorithm does?

2020-06-06 05:40 UTC, peasant98 commented on robotic_skin/calibration/optimizer.py
> +class TorchOptimizerBase(IncrementalOptimizerBase):
yes

2020-06-06 05:46 UTC, peasant98 commented on robotic_skin/calibration/transformation_matrix.py
> +        qz = pyqt.Quaternion(axis=[0, 0, 1], angle=temp_params[0])
yea, not sure what I was doing here.

2020-06-07 05:57 UTC, peasant98 commented on robotic_skin/calibration/transformation_matrix.py
> +        qz = pyqt.Quaternion(axis=[0, 0, 1], angle=temp_params[0])
fixed.

2020-06-07 07:06 UTC, peasant98 commented on robotic_skin/calibration/transformation_matrix.py
> +            temp_params = np.array([theta.cpu(), d.cpu(), a.cpu(), alpha.cpu()], dtype=float)
fixed

2020-06-07 07:06 UTC, peasant98 commented on robotic_skin/calibration/optimizer.py
> +class TorchOptimizerBase(IncrementalOptimizerBase):
done.

2020-06-07 07:07 UTC, peasant98 commented
merging once build passes.

2020-06-07 16:28 UTC, watakandai approved these changes

2020-06-07 16:53 UTC, merged