Refactoring Error Functions
HIRO-group/roboskin pull request #81
Opened 2020-05-18 17:56 UTC by bjkim00

This PR opens up my work in progress to refactor the error functions.

2020-05-18 17:59 UTC, watakandai commented
Nice work @bjkim00

2020-05-18 18:00 UTC, peasant98 commented
Cool

2020-05-20 17:38 UTC, watakandai commented
@peasant98 Are we not combining `estimate_acceleration_numerically` and `estimate_acceleration_analytically`?

2020-05-22 05:11 UTC, watakandai requested changes

2020-05-22 05:11 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +    w_dofd, a_dofd, a_centric_su = initialize_acceleration_variables(curr_w, dof_T_su)
Wait, if you have combined analytical and numerical solutions, do you need to make these lines separate functions?

2020-05-22 05:11 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
>      su_R_rs = rs_T_su.R.T
Define this before analytical solution, so that you can use it for `g_su = np.dot(su_R_rs, gravity)`

2020-05-22 05:11 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +                                                        joint_angle_func=max_acceleration_joint_angle,
Should we delete `constant_velocity_joint_angle`? We don't need it anymore, so that the function would look cleaner?

2020-05-22 05:11 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +    a_rs = ((positions[0] + positions[1] - 2*positions[2]) / (dt**2))
Should we make this for loop a function called `current_su_position()`?

```python
def current_su_position(kinematic_chain, curr_w, max_w, i_su, d_joint, t):
        angle = joint_angle_func(curr_w, max_w, t)
        dof_T_dof, rs_T_dof = kinematic_chain.get_current_TMs()
        kinematic_chain.add_a_pose(
            i_joint=d_joint,
            pose=angle,
            dof_T_dof=dof_T_dof,
            rs_T_dof=rs_T_dof)
        T = kinematic_chain._compute_su_TM(i_su, dof_T_dof, rs_T_dof)
        return T.position
```

2020-05-22 05:37 UTC, bjkim00 commented on robotic_skin/calibration/error_functions.py
> +    w_dofd, a_dofd, a_centric_su = initialize_acceleration_variables(curr_w, dof_T_su)
Do you want me to just combine them into one function and have it return the 5 variables? I agree that would make it look clearner

2020-05-22 05:39 UTC, bjkim00 commented on robotic_skin/calibration/error_functions.py
>      su_R_rs = rs_T_su.R.T
Will do

2020-05-22 05:40 UTC, bjkim00 commented on robotic_skin/calibration/error_functions.py
> +                                                        joint_angle_func=max_acceleration_joint_angle,
If we're not using it, I think we could just get rid of it. What do you think @peasant98

2020-05-22 05:41 UTC, bjkim00 commented on robotic_skin/calibration/error_functions.py
> +    a_rs = ((positions[0] + positions[1] - 2*positions[2]) / (dt**2))
That's what I was thinking as well. If you would like, I can just make the change to make the loop into a function as you showed above.

2020-05-22 06:03 UTC, peasant98 commented on robotic_skin/calibration/error_functions.py
> +                                                        joint_angle_func=max_acceleration_joint_angle,
yes, delete it

2020-05-23 02:05 UTC, peasant98 approved these changes
lgtm

2020-05-23 02:47 UTC, watakandai requested changes

2020-05-23 02:47 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +def estimate_acceleration(kinematic_chain, d_joint, i_su, curr_w, max_w=0, joint_angle_func=None,
I don't think we need `joint_angle_func`?

2020-05-23 02:47 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +def estimate_acceleration(kinematic_chain, d_joint, i_su, curr_w, max_w=0, joint_angle_func=None,
Sub the content of `max_acceleration_joint_angle` to `current_su_position`

2020-05-23 02:48 UTC, watakandai commented on robotic_skin/calibration/error_functions.py
> +def estimate_acceleration(kinematic_chain, d_joint, i_su, curr_w, max_w=0, joint_angle_func=None,
Then we are good to go

2020-05-24 03:01 UTC, watakandai approved these changes

2020-05-24 04:45 UTC, merged